### ISSUE TITLE
Error compiling `@deep-root-angular:async-config:dump` lambda

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-microservices-root-angular1#115]
Error running `deepify compile prod ./ -m=deep-root-angular:async-config:dump --invalidate-cache`:

```
> deep-framework@1.10.30 prepare-production /private/var/folders/6n/2fm3xn19451851qzr0s464hh0000gn/T/tmp-1121god0Qm77HSMr/60986f551eb52579262e852163d00435_1485511616323/node_modules/deep-framework
> bash hooks/prepare_production.sh

Removing browser build due to uselessness
Removing script directory due to uselessness
Removing garbage (!*.{js,json} && !*/bin/*)
Removing README files
Removing tests, docs, examples, etc recursively
Removing *.min.js, *.angular.js, etc. browser files recursively
Removing empty files and directories
wrote npm-shrinkwrap.json

/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/lib.compiled/NodeJS/NpmListDependencies.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(exports,"__esModule",{value:!0}),exports.NpmListDependencies=void 0;var _createClass=function(){function a(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1,d.configurable=!0,"value"in d&&(d.writable=!0),Object.defineProperty(a,d.key,d)}}return function(b,c,d){return c&&a(b.prototype,c),d&&a(b,d),b}}(),_Bin=require("./Bin"),_Exec=require("../Helpers/Exec"),_NpmDependency=require("./NpmDependency"),_NpmDepsListException=require("./Exception/NpmDepsListException"),NpmListDependencies=exports.NpmListDependencies=function(){function a(b){_classCallCheck(this,a),this._path=b}return _createClass(a,[{key:"list",value:function(){var a=arguments.length<=0||void 0===arguments[0]?null:
b: The following problems were found in the package deep-system-async-config-dump@0.0.1:
  - missing: buffer-shims@^1.0.0, required by readable-stream@2.2.2

    at a.exports.NpmListDependencies._createClass.value (/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/lib.compiled/NodeJS/NpmListDependencies.js:1:1094)
    at deepDepsCache.hasFor.optimize (/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/bin/commands/compile/prod.js:145:32)
    at /Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/bin/commands/compile/prod.js:217:9
    at a.exports.WaitFor._createClass.value (/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/WaitFor.js:1:1932)
    at a.exports.WaitFor._createClass.value (/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/WaitFor.js:1:1811)
    at null._onTimeout (/Users/mgoria/.nvm/versions/node/v4.3.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/WaitFor.js:1:1784)
    at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by eistrati** [comment]
Not relevant anymore.
